"""auto update

Revision ID: 73c003b58e9d
Revises: 
Create Date: 2026-08-15 23:47:38.129950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73c003b58e9d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studio_apps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('style', sa.String(), nullable=False),
    sa.Column('versions_json', sa.String(), nullable=False),
    sa.Column('current_version_index', sa.Integer(), nullable=False),
    sa.Column('version_count', sa.Integer(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_studio_apps_id'), 'studio_apps', ['id'], unique=False)
    op.create_index(op.f('ix_studio_apps_local_id'), 'studio_apps', ['local_id'], unique=False)
    op.create_index(op.f('ix_studio_apps_user_id'), 'studio_apps', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_studio_apps_user_id'), table_name='studio_apps')
    op.drop_index(op.f('ix_studio_apps_local_id'), table_name='studio_apps')
    op.drop_index(op.f('ix_studio_apps_id'), table_name='studio_apps')
    op.drop_table('studio_apps')
    # ### end Alembic commands ###